### ISSUE TITLE
Creating a folder Junction to share scripts

### ISSUE THREAD

**Issue by Kayumiy** [LukeStampfli/EmbeddedFPSExample#7]
Can you explain in detail please?
I cannot run this in cmd. I have windows OS.

![image](https://user-images.githubusercontent.com/22438366/78277953-a7bd6300-7558-11ea-8022-e8f92940de7e.png)

**Comment by SamathyTheManathy** [comment]
I was able to get this to work by swapping the "Client shared folder" and "server shared folder" arguments. Its also worth noting that this command creates the junction folder and won't work if the folder already exists.

**Comment by LukeStampfli** [comment]
I've improved the explanation of the mklink process a bit. I hope it is easier to comprehend now.
